export type ConsoleLocale = "en" | "ja" | "zh";

type LocaleTable<T> = Record<ConsoleLocale, T>;
const select = <T>(table: LocaleTable<T>, locale: ConsoleLocale): T => table[locale];

export const layoutCopy = (locale: ConsoleLocale) => select({
  en: { menu: "Menu", management: "Manage", knowledge: "Knowledge management", organization: "People and organization", system: "System operations", teamSetup: "Use with a team" },
  ja: { menu: "メニュー", management: "管理", knowledge: "知識管理", organization: "ユーザー・組織", system: "システム運用", teamSetup: "チームで使う" },
  zh: { menu: "菜单", management: "管理", knowledge: "知识管理", organization: "用户与组织", system: "系统运维", teamSetup: "与团队一起使用" }
}, locale);

const NAV_LABELS = {
  decisions: { en: "Decisions", ja: "決定", zh: "决策" }, map: { en: "Map", ja: "マップ", zh: "地图" }, skills: { en: "Skills", ja: "スキル", zh: "技能" }, agents: { en: "Agents", ja: "エージェント", zh: "代理" }, reviews: { en: "Reviews", ja: "レビュー", zh: "审核" },
  activity: { en: "Activity", ja: "活動", zh: "活动" }, connections: { en: "Knowledge connections", ja: "知識のつながり", zh: "知识关联" }, history: { en: "Knowledge history", ja: "知識の履歴", zh: "知识历史" }, tasks: { en: "Tasks", ja: "タスク", zh: "任务" }, dashboard: { en: "Dashboard", ja: "ダッシュボード", zh: "仪表盘" }, memories: { en: "Memories", ja: "メモリ", zh: "记忆" },
  "memory-explorer": { en: "Memory Explorer", ja: "メモリエクスプローラー", zh: "记忆浏览器" }, "memory-impact": { en: "Memory impact", ja: "活用分析", zh: "记忆活用分析" }, "decision-editor": { en: "Decision Editor", ja: "決定の作成・編集", zh: "决策编辑器" }, resources: { en: "Storage & resources", ja: "保存先・資料・成果物", zh: "存储与资料" }, "domain-packs": { en: "Domain Packs", ja: "ドメインパック", zh: "领域包" }, "domain-workspaces": { en: "Pack Workspaces", ja: "パック用ワークスペース", zh: "领域包工作区" }, "domain-metrics": { en: "Domain Metrics", ja: "業務指標", zh: "业务指标" }, "knowledge-history": { en: "Knowledge history", ja: "知識の履歴", zh: "知识历史" },
  groups: { en: "Groups", ja: "グループ", zh: "群组" }, users: { en: "Users", ja: "ユーザー", zh: "用户" }, organization: { en: "Organization", ja: "組織", zh: "组织" }, categories: { en: "Business Categories", ja: "業務カテゴリ", zh: "业务类别" }, clients: { en: "Client installations", ja: "クライアント接続", zh: "客户端连接" }, operations: { en: "Operations", ja: "運用", zh: "运维" }, profile: { en: "Profile", ja: "プロフィール", zh: "个人资料" }, "new-task": { en: "New task", ja: "タスク作成", zh: "新建任务" }, "team-setup": { en: "Use with a team", ja: "チームで使う", zh: "与团队一起使用" }
} as const satisfies Record<string, LocaleTable<string>>;

export const layoutNavLabels = (id: keyof typeof NAV_LABELS): LocaleTable<string> => NAV_LABELS[id];

export const memoryExplorerCopy = (locale: ConsoleLocale) => select({
  en: { title: "Memory Explorer", eyebrow: "Memory workspace", map: "Knowledge connections", fallbackTitle: "The accessible list is active", fallbackBody: "3D rendering is unavailable in this environment. The same filtered memories remain available here.", errorTitle: "Some memory information is unavailable", search: "Search", profile: "Profile", maintenance: "Maintenance", quality: "Quality", mine: "My memories", org: "Organization memories", active: "Active", review: "Needs review", trash: "Trash", scope: "Memory scope", lifecycle: "Memory lifecycle", page: "Page", previous: "Previous", next: "Next", emptyTitle: "No memories found", emptyBody: "No memories match this tenant and project. Adjust the filters or capture the first memory." },
  ja: { title: "メモリエクスプローラー", eyebrow: "メモリワークスペース", map: "知識のつながり", fallbackTitle: "検索・一覧表示に切り替えました", fallbackBody: "この環境では3D描画を利用できません。同じ条件のメモリをこの一覧で確認できます。", errorTitle: "一部のメモリ情報を取得できません", search: "検索", profile: "プロファイル", maintenance: "メンテナンス", quality: "品質", mine: "自分のメモリ", org: "組織のメモリ", active: "有効", review: "要確認", trash: "ゴミ箱", scope: "メモリの範囲", lifecycle: "メモリの状態", page: "ページ", previous: "前へ", next: "次へ", emptyTitle: "メモリが見つかりません", emptyBody: "このテナントとプロジェクトに一致するメモリはありません。条件を変更するか、最初のメモリを登録してください。" },
  zh: { title: "记忆浏览器", eyebrow: "记忆工作区", map: "知识关联", fallbackTitle: "已切换到搜索与列表", fallbackBody: "此环境无法使用3D渲染，仍可在此查看相同筛选条件下的记忆。", errorTitle: "部分记忆信息不可用", search: "搜索", profile: "配置", maintenance: "维护", quality: "质量", mine: "我的记忆", org: "组织记忆", active: "有效", review: "需要检查", trash: "回收站", scope: "记忆范围", lifecycle: "记忆状态", page: "页", previous: "上一页", next: "下一页", emptyTitle: "未找到记忆", emptyBody: "此租户和项目没有匹配的记忆。请调整筛选条件或记录第一条记忆。" }
}, locale);

export const groupsCopy = (locale: ConsoleLocale) => select({
  en: { title: "Groups", create: "Create group", name: "Name", slug: "Slug", description: "Description", details: "Details", empty: "No groups yet.", created: "Created", createError: "Group could not be created", loadError: "Groups could not be loaded" },
  ja: { title: "グループ", create: "グループを作成", name: "名前", slug: "識別子", description: "説明", details: "詳細", empty: "グループはまだありません。", created: "作成しました", createError: "グループを作成できませんでした", loadError: "グループを取得できませんでした" },
  zh: { title: "群组", create: "创建群组", name: "名称", slug: "标识符", description: "说明", details: "详情", empty: "尚无群组。", created: "已创建", createError: "无法创建群组", loadError: "无法加载群组" }
}, locale);

export const organizationCopy = (locale: ConsoleLocale) => select({
  en: { title: "Organization", displayName: "Display name", slug: "Slug", domains: "Allowed email domains", selfRegistration: "Allow email self-registration", save: "Save", saved: "Saved", saveError: "Organization could not be saved", ownership: "Memory ownership", mappings: "Producer → owner mappings", mappingBody: "Connect memories recorded by a service or agent identity to the responsible business owner.", producer: "Producer identity ID", owner: "Owner identity ID", principalHelp: "An identity ID (principal) is the stable internal identifier for a user, service, or AI agent. It does not grant access by itself.", saveMapping: "Save mapping", mappingSaved: "Ownership mapping saved", mappingError: "Ownership mapping could not be saved", updated: "Updated", empty: "No producer-owner mappings yet." },
  ja: { title: "組織設定", displayName: "表示名", slug: "識別子", domains: "許可するメールドメイン", selfRegistration: "メールでの自己登録を許可", save: "保存", saved: "保存しました", saveError: "組織設定を保存できませんでした", ownership: "メモリの所有者", mappings: "記録者 → 所有者の対応", mappingBody: "サービスやAIエージェントが記録したメモリを、業務上の所有者へ明示的に結び付けます。", producer: "記録元のID", owner: "所有者のID", principalHelp: "ID（principal）は、ユーザー・サービス・AIエージェントを区別する内部識別子です。IDだけでアクセス権が付与されることはありません。", saveMapping: "対応を保存", mappingSaved: "所有者の対応を保存しました", mappingError: "所有者の対応を保存できませんでした", updated: "更新日時", empty: "記録者と所有者の対応はまだありません。" },
  zh: { title: "组织设置", displayName: "显示名称", slug: "标识符", domains: "允许的邮箱域名", selfRegistration: "允许邮箱自助注册", save: "保存", saved: "已保存", saveError: "无法保存组织设置", ownership: "记忆所有权", mappings: "记录者 → 所有者映射", mappingBody: "将服务或代理记录的记忆明确关联到业务负责人。", producer: "记录者身份 ID", owner: "所有者身份 ID", principalHelp: "身份 ID（principal）是用户、服务或 AI 代理的稳定内部标识，本身不会授予访问权限。", saveMapping: "保存映射", mappingSaved: "已保存所有权映射", mappingError: "无法保存所有权映射", updated: "更新时间", empty: "尚无记录者与所有者映射。" }
}, locale);

export const clientInstallationsCopy = (locale: ConsoleLocale) => select({
  en: { title: "Client installations", body: "Manage unattended hook credentials for Codex, Claude Code, and Cursor by machine and client. Interactive OAuth sessions remain managed by Cloudflare Access and each client.", revoked: "Client installation revoked.", revokeError: "Client installation could not be revoked.", pending: "Pending client installation created.", createError: "Client installation could not be created", oneTime: "This enrollment code is shown only once", expires: "Expires", secretNote: "Store it securely and separately from the service-token secret.", client: "Client", device: "Device label", devicePlaceholder: "Work Mac", create: "Create enrollment", created: "Created", lastUsed: "Last used", never: "Never used", revoke: "Revoke", empty: "No client installations yet.", command: "Copy setup command", copied: "Copied", verify: "Connection check", verifyBody: "Run the command, then confirm that this installation becomes Active and Last used is updated.", recovery: "If setup fails, revoke this installation and create a new enrollment. The code cannot be shown again." },
  ja: { title: "クライアント接続", body: "Codex、Claude Code、Cursorの無人hook用認証情報を端末・クライアント単位で管理します。対話型OAuthセッションはCloudflare Accessと各クライアントが管理します。", revoked: "クライアント接続を無効化しました。", revokeError: "クライアント接続を無効化できませんでした。", pending: "保留中のクライアント接続を作成しました。", createError: "クライアント接続を作成できませんでした", oneTime: "登録コードは今回だけ表示されます", expires: "有効期限", secretNote: "サービストークンのシークレットとは分けて安全に保管してください。", client: "クライアント", device: "端末名", devicePlaceholder: "業務用Mac", create: "登録を作成", created: "作成日時", lastUsed: "最終利用", never: "未使用", revoke: "無効化", empty: "クライアント接続はまだありません。", command: "セットアップコマンドをコピー", copied: "コピーしました", verify: "接続確認", verifyBody: "コマンド実行後、この接続が利用中になり「最終利用」が更新されることを確認してください。", recovery: "失敗した場合はこの接続を無効化し、新しい登録を作成してください。コードは再表示できません。" },
  zh: { title: "客户端连接", body: "按设备和客户端管理 Codex、Claude Code 与 Cursor 的无人值守 hook 凭据。交互式 OAuth 会话仍由 Cloudflare Access 和各客户端管理。", revoked: "已撤销客户端连接。", revokeError: "无法撤销客户端连接。", pending: "已创建待处理的客户端连接。", createError: "无法创建客户端连接", oneTime: "此注册码仅显示一次", expires: "有效期至", secretNote: "请与 service token 密钥分开安全保存。", client: "客户端", device: "设备名称", devicePlaceholder: "工作 Mac", create: "创建注册", created: "创建于", lastUsed: "最后使用", never: "从未使用", revoke: "撤销", empty: "尚无客户端连接。", command: "复制设置命令", copied: "已复制", verify: "连接检查", verifyBody: "运行命令后，请确认此连接变为活动状态且最后使用时间已更新。", recovery: "如果设置失败，请撤销此连接并创建新注册。注册码无法再次显示。" }
}, locale);

export const taskListTitle = (locale: ConsoleLocale) => select({ en: "Tasks · Org Brain", ja: "タスク一覧 · Org Brain", zh: "任务 · Org Brain" }, locale);

export const taskDashboardCopy = (locale: ConsoleLocale) => select({
  en: { title: "Org Brain Tasks", description: "Recent tasks and their current status.", preview: "Task list", search: "Search tasks", searchPlaceholder: "ID, capability, or project", status: "Status", all: "All statuses", apply: "Apply", clear: "Clear", currentPage: "Status on this page", results: "Showing {count}{suffix} tasks · Page {page}", empty: "No tasks match the current scope.", unavailable: "Tasks could not be loaded", retry: "Retry", taskId: "Task ID", capability: "Capability", updated: "Updated", previous: "Previous", next: "Next", more: "More tasks are available on the next page.", tenant: "Tenant", pagination: "Task pagination" },
  ja: { title: "Org Brain タスク一覧", description: "最近のタスクと現在のステータスを確認します。", preview: "タスク一覧", search: "タスクを検索", searchPlaceholder: "ID・処理名・プロジェクト", status: "ステータス", all: "すべてのステータス", apply: "適用", clear: "クリア", currentPage: "このページのステータス", results: "{count}件{suffix}を表示 · {page}ページ目", empty: "現在の範囲に一致するタスクはありません。", unavailable: "タスクを取得できませんでした", retry: "再試行", taskId: "タスクID", capability: "処理", updated: "更新日時", previous: "前へ", next: "次へ", more: "次のページに続きがあります。", tenant: "テナント", pagination: "タスクのページ" },
  zh: { title: "Org Brain 任务", description: "查看最近的任务及其当前状态。", preview: "任务列表", search: "搜索任务", searchPlaceholder: "ID、能力或项目", status: "状态", all: "所有状态", apply: "应用", clear: "清除", currentPage: "本页状态", results: "显示 {count}{suffix} 个任务 · 第 {page} 页", empty: "当前范围内没有匹配的任务。", unavailable: "无法获取任务", retry: "重试", taskId: "任务 ID", capability: "能力", updated: "更新时间", previous: "上一页", next: "下一页", more: "下一页还有更多任务。", tenant: "租户", pagination: "任务分页" }
}, locale);

export const taskCreateCopy = (locale: ConsoleLocale) => select({
  en: { title: "Create Task", heading: "Create Task", tenant: "Tenant ID", project: "Project ID", capability: "Capability", inputRef: "Input reference", inputPlaceholder: "r2://... or memory://... or plain text", submit: "Create Task", pending: "Not submitted" },
  ja: { title: "タスク作成", heading: "タスク作成", tenant: "テナントID", project: "プロジェクトID", capability: "処理", inputRef: "入力元", inputPlaceholder: "r2://... または memory://... またはテキスト", submit: "タスクを作成", pending: "未送信" },
  zh: { title: "新建任务", heading: "新建任务", tenant: "Tenant ID", project: "项目 ID", capability: "能力", inputRef: "输入引用", inputPlaceholder: "r2://... 或 memory://... 或纯文本", submit: "创建任务", pending: "尚未提交" }
}, locale);

export const taskDetailCopy = (locale: ConsoleLocale) => select({
  en: { title: "Task detail", taskId: "Task ID", capability: "Process", status: "Status", project: "Project", updated: "Updated", priority: "Priority", timeline: "Event timeline", kind: "Kind", at: "At", payload: "Details", empty: "No events have been recorded yet.", notFoundTitle: "Task not found", notFoundBody: "It may have been removed or it may belong to a different tenant or project.", taskErrorTitle: "Task details could not be loaded", taskErrorBody: "The service did not return a usable response. Retry before making an operational decision.", eventsErrorTitle: "Some event history is unavailable", eventsErrorBody: "The Task was loaded, but its event timeline could not be retrieved.", back: "Back to Tasks", retry: "Retry", operations: "Open Operations", replay: "Replay Task", replaying: "Creating a replay Task…", replayed: "Replay Task created", replayError: "The Task could not be replayed." },
  ja: { title: "タスク詳細", taskId: "タスクID", capability: "処理", status: "状態", project: "プロジェクト", updated: "更新日時", priority: "優先度", timeline: "イベント履歴", kind: "種類", at: "発生日時", payload: "内容", empty: "イベントはまだ記録されていません。", notFoundTitle: "タスクが見つかりません", notFoundBody: "削除されたか、別のテナントまたはプロジェクトに属している可能性があります。", taskErrorTitle: "タスク詳細を取得できませんでした", taskErrorBody: "サービスから利用可能な応答がありません。運用判断の前に再試行してください。", eventsErrorTitle: "イベント履歴の一部を取得できませんでした", eventsErrorBody: "タスク本体は取得できましたが、イベント履歴を読み込めませんでした。", back: "タスク一覧へ戻る", retry: "再試行", operations: "運用画面を開く", replay: "タスクを再実行", replaying: "再実行タスクを作成しています…", replayed: "再実行タスクを作成しました", replayError: "タスクを再実行できませんでした。" },
  zh: { title: "任务详情", taskId: "任务 ID", capability: "处理", status: "状态", project: "项目", updated: "更新时间", priority: "优先级", timeline: "事件记录", kind: "类型", at: "时间", payload: "内容", empty: "尚未记录事件。", notFoundTitle: "未找到任务", notFoundBody: "该任务可能已被删除，或属于其他租户或项目。", taskErrorTitle: "无法加载任务详情", taskErrorBody: "服务未返回可用响应，请在做出运维判断前重试。", eventsErrorTitle: "部分事件记录不可用", eventsErrorBody: "任务已加载，但无法获取事件记录。", back: "返回任务列表", retry: "重试", operations: "打开运维页面", replay: "重新运行任务", replaying: "正在创建重试任务…", replayed: "已创建重试任务", replayError: "无法重新运行任务。" }
}, locale);

export const domainPacksCopy = (locale: ConsoleLocale) => select({
  en: { title: "Domain Packs", heading: "Install a business domain as one package", body: "Preview and apply managed objects, metrics, dashboards, connector references, skills, and workflows together. High-frequency raw data and secrets are never included.", selectError: "Select at least one pack.", previewError: "The installation preview could not be created.", installError: "The pack could not be installed.", installed: "packs installed. No fixture data was added.", available: "Available", installedState: "Installed", objects: "Objects", metrics: "Metrics", assets: "Operational assets", connector: "Connectors", details: "Review contents", preview: "Preview installation changes", apply: "Install selected packs", fixtureNote: "A normal installation does not add examples/story-v1.json.", customPreserved: "Custom definitions with the same name are preserved." },
  ja: { title: "ドメインパック", heading: "業務ドメインをひとまとまりで導入", body: "管理対象、指標、ダッシュボード、コネクター参照、スキル・ワークフロー参照を確認して一括適用します。高頻度の生データと秘密情報はパックに含まれません。", selectError: "パックを1つ以上選択してください。", previewError: "導入内容の確認を作成できませんでした。", installError: "パックを適用できませんでした。", installed: "件のパックを適用しました。評価用データは投入していません。", available: "利用可能", installedState: "導入済み", objects: "対象", metrics: "指標", assets: "運用資産", connector: "コネクター", details: "内容を確認", preview: "導入差分を確認", apply: "選択したパックを適用", fixtureNote: "通常の導入では examples/story-v1.json を投入しません。", customPreserved: "同名のカスタム定義は維持されます。" },
  zh: { title: "领域包", heading: "将业务领域作为一个整体安装", body: "预览并统一应用管理对象、指标、仪表盘、连接器引用、技能和工作流。不会包含高频原始数据和秘密。", selectError: "请至少选择一个领域包。", previewError: "无法创建安装预览。", installError: "无法安装领域包。", installed: "个领域包已安装，未添加样例数据。", available: "可用", installedState: "已安装", objects: "对象", metrics: "指标", assets: "运维资产", connector: "连接器", details: "查看内容", preview: "预览安装差异", apply: "安装所选领域包", fixtureNote: "正常安装不会添加 examples/story-v1.json。", customPreserved: "同名的自定义定义会被保留。" }
}, locale);
